name: alice

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  format:
    exec: dart format .
  test:
    description: Run tests in a specific package.
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true